const verifikasiDokumenItem = [
  {
    id: "URSBY1234567891",
    pemohon: "Regi Muhammar1",
    perizinan: "Pembangunan TK",
    tanggal: "13 November 2023",
    status: "Terlambat",
    status_survey: "Sudah Survey",
    link: "/kelengkapan-dokumen-operator",
    link_2: "/kelengkapan-dokumen-verifikator",
    link_3: "/detail-pengesahan-verifikator",
  },
  {
    id: "URSBY1234567892",
    pemohon: "Regi Muhammar2",
    perizinan: "Pembangunan TK",
    tanggal: "13 November 2023",
    status: "Terlambat",
    status_survey: "Sedang Survey",
    link: "/kelengkapan-dokumen-operator",
    link_2: "/kelengkapan-dokumen-verifikator",
    link_3: "/detail-pengesahan-verifikator",
  },
  {
    id: "URSBY1234567893",
    pemohon: "Regi Muhammar3",
    perizinan: "Pembangunan TK",
    tanggal: "13 November 2023",
    status: "Selesai",
    status_survey: "Sedang Survey",
    link: "/kelengkapan-dokumen-operator",
    link_2: "/kelengkapan-dokumen-verifikator",
    link_3: "/detail-pengesahan-verifikator",
  },
  {
    id: "URSBY1234567894",
    pemohon: "Regi Muhammar4",
    perizinan: "Pembangunan TK",
    tanggal: "13 November 2023",
    status: "Perlu Verifikasi",
    status_survey: "Sudah Survey",
    link: "/kelengkapan-dokumen-operator",
    link_2: "/kelengkapan-dokumen-verifikator",
    link_3: "/detail-pengesahan-verifikator",
  },
  {
    id: "URSBY1234567895",
    pemohon: "Regi Muhammar5",
    perizinan: "Pembangunan TK",
    tanggal: "13 November 2023",
    status: "Terlambat",
    status_survey: "Sedang Survey",
    link: "/kelengkapan-dokumen-operator",
    link_2: "/kelengkapan-dokumen-verifikator",
    link_3: "/detail-pengesahan-verifikator",
  },
  {
    id: "URSBY1234567896",
    pemohon: "Regi Muhammar6",
    perizinan: "Pembangunan TK",
    tanggal: "13 November 2023",
    status: "Terlambat",
    status_survey: "Sedang Survey",
    link: "/kelengkapan-dokumen-operator",
    link_2: "/kelengkapan-dokumen-verifikator",
    link_3: "/detail-pengesahan-verifikator",
  },
];

export default verifikasiDokumenItem;
